version: '2.3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/src
      - ./run/home/ubuntu:/home/ubuntu
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.ssh/id_rsa.pub:/home/ubuntu/.ssh/authorized_keys
    working_dir: /src
    ports:
      - "8822:22"
      - "9090:9090"
